using Content.Shared.Calculator.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Shared.Calculator.Components.CalculatorComponent;

namespace Content.Client.Calculator.UI;

[GenerateTypedNameReferences]
public sealed partial class CalculatorWindow : DefaultWindow
{
    private readonly Dictionary<string, Button> _buttons = new();

    public CalculatorWindow()
    {
        RobustXamlLoader.Load(this);

        FillInputGrid();
    }

    public void UpdateState(IPrototypeManager prototypeManager, CalculatorBoundUserInterfaceState state)
    {
        //Update shit
    }

    void FillInputGrid()
    {

    }

    void AddNumberButton(byte i)
    {
        var button = new Button
        {
            Name = $"{i}",
        };

        button.OnPressed += _ =>
        {
            //TODO: ADD BUTTON BEHAVIOR
        };

        InputGrid.
    }
}
