using Content.Shared.Calculator.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Shared.Calculator.Components.CalculatorComponent;

namespace Content.Client.Calculator.UI;

[GenerateTypedNameReferences]
public sealed partial class CalculatorWindow : DefaultWindow
{
    private readonly Dictionary<string, Button> _buttons = new();

    public CalculatorWindow()
    {
        RobustXamlLoader.Load(this);

        FillInputGrid();
    }

    public void UpdateState(IPrototypeManager prototypeManager, CalculatorBoundUserInterfaceState state)
    {
        //Update shit
    }

    void FillInputGrid()
    {
        for (int i = 0; i < 6 * 4; i++)
        {
            AddNumberButton(i);
        }
    }

    void AddNumberButton(int i)
    {
        var button = new Button
        {
            Text = $"{i}",
        };

        button.OnPressed += _ =>
        {
            //TODO: ADD BUTTON BEHAVIOR
        };

        InputGrid.AddChild(button);
    }
}
